### ISSUE TITLE
Graph Manager - Unknown directive "cypher"

### ISSUE THREAD

**Issue by AdrienLemaire** [grand-stack/grand-stack-starter#66]
While following the [Apollo basics tutorial](https://www.apollographql.com/docs/tutorial/production/#publish-your-schema-to-graph-manager), I tried to run

```console
$ npx apollo service:push --graph=neo4j --key=user:<user>:<hash> --localSchemaFile=src/schema.graphql
```
from my repo created by following grand-stack-starter.

It fails with the following error:
![](https://i.imgur.com/usxjufZ.png)

Is it not possible to use the Apollo Graph Manager with a GRANDstack? Or could you explain how to configure the graph manager with these neo4j-graphql specific directives?

**Comment by johnymontana** [comment]
Thanks for reporting @AdrienLemaire. The problem is that the type definitions used by neo4j-graphql.js are not really the full "schema". The `makeAugmentedSchema` process goes through a transformation process which adds input types, directive declarations, etc.

So one option would be to get the full GraphQL schema and push that to Apollo Graph Manager. An easy way to do this is to look at the "schema" tab in GraphQL Playground, or use the `printSchema` function from graphql-js.

Another option would be to add the missing directive declarations to your typedefs:


```
directive @cypher(statement: String) on FIELD_DEFINITION
directive @relation(name: String, direction: _RelationDirections, from: String, to: String) on FIELD_DEFINITION | OBJECT
```

**Comment by AdrienLemaire** [comment]
Thanks @johnymontana ! That's what I finally understood yesterday on https://github.com/neo4j-graphql/neo4j-graphql-js/issues/442

I settled by calling the graphql endpoint when running codegen to get the augmented schema

```js
module.exports = {
  client: {
    name: "Project [web]",
    service: {
      name: "project",
      // This option uses the resulting schema from makeAugmentedSchema
      url: "http://localhost:4001/graphql",
      skipSSLValidation: true,
    }
}
```

If you know what the remaining `[GraphQL error]: 406: Not Acceptable` error is about, I'd really appreciate if you could share your hindsight on that other issue.
Closing this one :)
