### ISSUE TITLE
run seedDb script not where documentation implies

### ISSUE THREAD

**Issue by kimcs** [grand-stack/grand-stack-starter#91]
I was finally able to run the command `npm run seedDb` after i discovered that I needed to be in the `api` subfolder for this to work. This is not reflected in the documentation.

Also the seedDb command for docker at the bottom of the README does not work either, perhaps this is a similar issue?

**Comment by udaykor** [comment]
@kimcs I have been able to use the seedDb. Infact, I have used this starter as a way for me to get my own react app become a grand stack. 

In the README, this is marked as optional step. 

Did you have issues running seedDB? What is the error you see? Can you help explain more on what happens when you run seedDB. Is your Graphql docker container up?

**Comment by KavitaKirdkude** [comment]
I am also facing the issue with `seedDb` command. 

I have followed the GrandStack starter project to create my first GrandStack application. I have created the Neo4J sandbox with the blank database and added the respective information into the `.env` file. 

When I try to run the command `npm run seedDb` in a separate terminal within the "api" folder, the command fails and the Database is not seeded. The error I am receiving is -

`Error: Error: Network error: Unexpected end of JSON input
    at C:\Kavita\GrandStackProjects\networkManagementApp\api\src\seed\/seed-db.js:36:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)`

I have verified that the mutations that I am getting from the method `getSeedMutations()` is a valid JSON. 

I am unable to find any solution for the same. Is anyone facing similar issue and found any solution?

**Comment by ed42311** [comment]
@kimcs Thanks for checking out the template, going to break this down into separate issues, because these seem to be separate items.  The one I would like to address is the one in the title.

> I was finally able to run the command npm run seedDb after i discovered that I needed to be in the api subfolder for this to work. This is not reflected in the documentation.

You are right about that, built a script connector and updated the documentation to reflect updates here:  https://github.com/grand-stack/grand-stack-starter/pull/104

I broke the docker issue out:
https://github.com/grand-stack/grand-stack-starter/issues/103

**Comment by ed42311** [comment]
@KavitaKirdkude you might be running into a seperate issue.
Created https://github.com/grand-stack/grand-stack-starter/issues/105

**Comment by ed42311** [comment]
Going to close this issue withe docs update branch and moving other non-related issues
